server1         ansible_host=xxxxxx        ansible_user=xxxxx  ansible_password=xxxxxansible_ssh_common_args='-o StrictHostKeyChecking=no'
server2         ansible_host=xxxx    ansible_user=xxxxx  ansible_password=xxxxxansible_ssh_common_args='-o StrictHostKeyChecking=no'
server3         ansible_host=xxxx       ansible_user=xxxxx  ansible_password=xxxxxansible_ssh_common_args='-o StrictHostKeyChecking=no'
server4         ansible_host=xxxx        ansible_user=xxxxx  ansible_password=xxxxxansible_ssh_common_args='-o StrictHostKeyChecking=no'


